language: objective-c
cache: cocoapods
xcode_sdk: iphonesimulator9.0
osx_image: xcode8.2
xcode_project: Lighthouse Camera.xcodeproj
xcode_scheme: Lighthouse Camera Travis Tests

before_script:
  # Make outputs more readable.
  - gem install xcpretty-travis-formatter
  # Install OpenCV binary.
  - unzip 3rdparty/opencv-ios.zip -d Lib/

# The default script uses xctool, which doesn't work anymore. Overriding.
script:
  - xcodebuild build -project "Lighthouse Camera.xcodeproj" -scheme "Lighthouse Camera Travis Tests" -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}

